name: Autoformat code
on: pull_request

# This action only need a single permission in order to autoformat the code.
permissions:
  contents: read

jobs:
  autoformat-code:
    name: Autoformat code
    runs-on: ubuntu-latest

    steps:
    - name: 'Autoformat'
      uses: rolfbjarne/autoformat@94fa87fa489a46bcd29bfd75eba08c658fbabe62
      with:
        projects: "testproject/testproject.csproj"
        onlyFilesModifiedInPullRequest: true
