name: Autoformat code
on: pull_request

jobs:
  autoformat-code:
    name: Autoformat code
    runs-on: ubuntu-latest

    steps:
    - name: 'Autoformat'
      uses: rolfbjarne/autoformat@v0.1
      with:
        projects: "testproject/testproject.csproj testproject/testproject.csproj"
